### ISSUE TITLE
Allow passing arguments via environment variable `PLUGIN_CONFIG`

### ISSUE THREAD

**Issue by bt** [Secoura/eventgen#2]
Right now the only way to pass arguments is via a command-line. Discover's plugin system works by passing a JSON object via environment variable `PLUGIN_CONFIG`.

`eventgen` needs to consider either one or the other for reading configuration from. It should then unmarshal the JSON object and match those up with the arguments that could be configured on the command line.

For example, a PLUGIN_CONFIG could be:

```json
{
  "template": "web",
  "startTime": "08/Apr/2018:15:04:05 +1000",
  "duration" "15m"
  ...
}
```

If the above configuration was used, it should also be **an error** due to the fact that the key `noOfEvents` was not set and is a required config.

**Comment by yeoji** [comment]
Eventgen will now try to read from the environment variable `PLUGIN_CONFIG` and if it fails, fall back to trying the `config.yaml` file.
