### ISSUE TITLE
Introduce `parsed` flag

### ISSUE THREAD

**Issue by bt** [Secoura/eventgen#7]
We need to introduce a new flag that allows output of parsed output instead of unprocessed output.

Currently, we get output like the following:

```
25.73.68.199 - - [30/May/2018:14:21:20 +1000] “POST /Kwimbee-Remote-Disc-Filter HTTP/1.1” 404 25882 “-“ “Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2; rv:10.0.1) Gecko/20100101 Firefox/10.0.1”
```

This is great for doing stress testing, but in a case where we just want to use `eventgen` for generating demo data, we'd want to skip all the processing and make the output ready to be indexed.

The same event above should be parsed to the following:

```
{
  "_raw": "25.73.68.199 - - [30/May/2018:14:21:20 +1000] \"POST /Kwimbee-Remote-Disc-Filter HTTP/1.1\" 404 25882 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2; rv:10.0.1) Gecko/20100101 Firefox/10.0.1\"",
  "_time": "2018-05-30T04:21:20Z",
  "clientip": "25.73.68.199",
  "ident": "-",
  "auth": "-",
  "verb": "POST",
  "request": "/Kwimbee-Remote-Disc-Filter",
  "httpversion": "1.1",
  "rawrequest": null,
  "response": "404",
  "bytes": "25882"
}
```

Note that it's as JSON object. Each line should be separated by line separator `\n` and contain a single event.

**Comment by yeoji** [comment]
Actually @bt, we only need to add a new template for this functionality.

I have added a sample in `demo/parsed`. You can take a look in the PR above 😄

**Comment by bt** [comment]
Hmm not sure if this will fly very well; there's two issues with this:

1. We'll need to maintain two sets of practically the same type of templates (eg. `parsed-combined` and `combined).
2. All messages will contain `_raw` which is the original raw message. The randomisation would happen in `_raw` but then a second set of values would be generated for a subsequent field?

**Comment by yeoji** [comment]
1. Yup, exactly the same as having `web/combined` and `web/common`.
2. No, processors run substitution: an example generated event would be:

```
{
  "_raw": "237.142.11.116 - - [08/Apr/2018:15:18:08 +1000] \"PUT /Mydeo-Air-Performance-Component HTTP/1.1\" 404 373",
  "_time": "08/Apr/2018:15:07:17Z",
  "clientip": "237.142.11.116",
  "ident": "-",
  "auth": "-",
  "verb": "PUT",
  "request": "/Mydeo-Air-Performance-Component",
  "httpversion": "1.1",
  "rawrequest": null,
  "response": "404",
  "bytes": "373"
}
```

**Comment by bt** [comment]
Oh then in that case, it might work.

**Comment by yeoji** [comment]
Awesome! I have merged the PR. Will close this issue now 🎉
